### ISSUE TITLE
RFC: This RFC repo/process is unnecessary and should be discontinued.

### ISSUE THREAD

**Issue by mcav** [fxbox/RFC#10]
We don't need a decoupled RFC repository. Few people "watch" this repository for changes (2, as of this writing), making it necessary to broadcast RFCs elsewhere. I don't see how this is any better, or as good as, posting GitHub issues in appropriate repositories.

**Comment by fabricedesre** [comment]
But how will people notice this one? ;)

**Comment by Yoric** [comment]
I believe that this is a much better place to put RFCs than random issues scattered across repos. Plus, having a dedicated repo works nicely for Rust, so it might work nicely for us, too :)

**Comment by Yoric** [comment]
Also, you will note that our discussion in https://github.com/fxbox/taxonomy/issues/63 is forum-style, while our discussion in https://github.com/fxbox/RFC/pull/9 lets us comment specific lines, which I believe is more convenient for a PR.

So I'd like to WONTFIX this issue :)

**Comment by mcav** [comment]
If we're going to follow an RFC process, we should:
1. Encourage the team to subscribe to this repo;
2. Establish a process for reaching consensus when parties don't agree;
3. Document this process, with prominent links from the other repos to here.

**Comment by Yoric** [comment]
Agreed on all three points.
